export const BABYLON_COMPONENT_ENGINE = 'BABYLON_COMPONENT_ENGINE';
export const BABYLON_COMPONENT_CAMERA = 'BABYLON_COMPONENT_CAMERA';
export const BABYLON_COMPONENT_LIGHT = 'BABYLON_COMPONENT_LIGHT';
export const BABYLON_COMPONENT_MESH = 'BABYLON_COMPONENT_MESH';
export const BABYLON_COMPONENT_MESH_SPHERE = 'BABYLON_COMPONENT_MESH_SPHERE';
export const BABYLON_COMPONENT_SCENE = 'BABYLON_COMPONENT_SCENE';
export const BABYLON_COMPONENT_VECTOR = 'BABYLON_COMPONENT_VECTOR';
